title: RFC1918 Blog
author: RFC1918 
description: >- # this means to ignore newlines until "baseurl:"
  ~#
permalink: /:categories/:title/
url: "rfc-infosec" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _rfc1918
github_username:  RFC1918-hub

# Build settings
remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme
  - jekyll-paginate

# site settings 
excerpt_separator: "<!--break-->"

# navigation sidebar
navigation:
  - {file: index.html}
  - {file: categories.html}
  - {file: search.html}

external:
  - {title: Github, icon: github, url: "https://github.com/RFC1918-hub"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/pinortje/"}

# pagination settings 
paginate: 5 # displays 5 posts per page
paginate_path: "/page:num/"

# google analytics
google_analytics: G-DCX88DHKT8
url: "https://rfc-infosec.com"